config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  resources :categories

  resources :spots

  resources :users do
    member do
      get 'spots'
    end
  end

  resources :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :spots
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :user

  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :spots

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  protected

  def not_authenticated
    redirect_to new_session_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to(spots_user_path(@user))
    else
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url
  end
  
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:new, :create, :edit]
  before_action :set_user, only: [:new, :create, :edit, :show]


  # GET /spots
  # GET /spots.json
  def index
    @spots = Spot.all
  end

  # GET /spots/1
  # GET /spots/1.json
  def show
  end

  # GET /spots/new
  def new
    @spot = Spot.new
  end

  # GET /spots/1/edit
  def edit
  end

  # POST /spots
  # POST /spots.json
  def create
    @spot = Spot.new(spot_params)
    respond_to do |format|
      if @spot.save
        format.html { redirect_to @spot, notice: 'Spot was successfully created.' }
        format.json { render :show, status: :created, location: @spot }
      else
        format.html { render :new }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spots/1
  # PATCH/PUT /spots/1.json
  def update
    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to @spot, notice: 'Spot was successfully updated.' }
        format.json { render :show, status: :ok, location: @spot }
      else
        format.html { render :edit }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1
  # DELETE /spots/1.json
  def destroy
    @spot.destroy
    respond_to do |format|
      format.html { redirect_to spots_url, notice: 'Spot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_spot
    @spot = Spot.find(params[:id])
  end

  def set_categories
    @categories = Category.all
  end

  def set_user
    @user = User.find(session[:user_id])
  end

  # Only allow a list of trusted parameters through.
  def spot_params
    params.require(:spot).permit(:user_id, :category_id, :name, :address, :postal_code, :neer_station)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :spots]
  skip_before_action :require_login, only: [:new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def spots
    @user_name = @user.name
    @categories = Category.all 
    if params[:category_id].present?
      @spots = @user.spots.where(category_id: params[:category_id])
    else
      @spots = @user.spots
    end
    
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.slim
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      h2 = "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      ul
        - @category.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/categories/edit.html.slim
h1 Editing category

== render 'form'

=> link_to 'Show', @category
'|
=< link_to 'Back', categories_path

app/views/categories/index.html.slim
h1 Listing categories

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @categories.each do |category|
      tr
        td = category.name
        td = link_to 'Show', category
        td = link_to 'Edit', edit_category_path(category)
        td = link_to 'Destroy', category, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Category', new_category_path

app/views/categories/new.html.slim
h1 New category

== render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.slim
p#notice = notice

p
  strong Name:
  = @category.name

=> link_to 'Edit', edit_category_path(@category)
'|
=< link_to 'Back', categories_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Barcelona</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'categoryLink', 'data-turbolinks-track': 'reload' %>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">barcelona</a>
      <% if current_user  %>
        <%= link_to('Logout',session_path, class: 'logout' , method: :delete) %>
      <% end%>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon">
           <a class="navbar-brand" href="/">logout</a>
          </span>
        </button>
    </nav>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/spots/_form.html.slim
= form_for @spot do |f|
  - if @spot.errors.any?
    #error_explanation
      h2 = "#{pluralize(@spot.errors.count, "error")} prohibited this spot from being saved:"
      ul
        - @spot.errors.full_messages.each do |message|
          li = message

  .row
  .container
      .col.s12.z-depth-6.card-panel
        .field
          = f.hidden_field :user_id, value: session[:user_id]

        .field
          = f.label :カテゴリー
          = f.collection_select :category_id, @categories, :id, :name, {}, class: "browser-default"

        .field 
          = f.label :店舗名
          = f.text_field :name, class: 'form-control'
        .field
          = f.label :郵便番号
          = f.text_field :postal_code, class: 'form-control'
        .field
          = f.label :住所
          = f.text_field :address, class: 'form-control'
        .field
          = f.label :最寄駅
          = f.text_field :neer_station, class: 'form-control'
        .row
        .actions.btn.waves-effect.waves-light.col.s12 = f.submit "登録"

        

app/views/spots/edit.html.slim
h1 = @spot.name + "を編集"

== render 'form'

.container

  => link_to '詳細を見る', @spot, class:"btn waves-effect waves-light"
  =< link_to '一覧へ戻る', spots_user_path(@user), class:"btn waves-effect waves-light"

app/views/spots/index.html.slim
h1 Listing spots

table
  thead
    tr
      th User
      th Name
      th Address
      th Postal code
      th Neer station
      th
      th
      th

  tbody
    - @spots.each do |spot|
      tr
        td = spot.user_id
        td = spot.name
        td = spot.address
        td = spot.postal_code
        td = spot.neer_station
        td = link_to 'Show', spot
        td = link_to 'Edit', edit_spot_path(spot)
        td = link_to 'Destroy', spot, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Spot', new_spot_path

app/views/spots/new.html.slim
h1 スポットを新規登録する

== render 'form'

.container
  = link_to '戻る', spots_user_path(@user), class:"btn waves-effect waves-light"

app/views/spots/show.html.slim
p#notice = notice

h1 = @spot.name + "の詳細"
.row
.container
  .col.s12.z-depth-6
    table 
      tr
        th ユーザー名
        td = @spot.user.name
  
      tr
        th カテゴリー
        td = @spot.category.name
  
      tr
        th 郵便番号
        td = @spot.postal_code
  
      tr
        th 郵便番号
        td = @spot.address

      tr
        th 最寄駅
        td = @spot.neer_station
    
    .row
    => link_to '編集', edit_spot_path(@spot), class:"btn waves-effect waves-light"
    =< link_to '戻る', spots_user_path(@user), class:"btn waves-effect waves-light"
  

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .actions = f.submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

=> link_to 'Show', @user
'|
=< link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Name
      th Email
      th
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.name
        td = user.email
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong Name:
  = @user.name
p
  strong Email:
  = @user.email

=> link_to 'Edit', edit_user_path(@user)
'|
=< link_to 'Back', users_path

app/views/users/spots.html.slim
h1 = @user.name + "のリスト一覧"

.container
  - @categories.each do |category|
    =label_tag
      =radio_button :check, "", category.id, class: "browser-default"
      span = category.name
  .row
  table.table.table-bordered
    thead
      tr
        th User
        th Category
        th Name
        th Address
        th Postal code
        th Neer station
        th
        th
        th

    tbody
      - @spots.each do |spot|
        tr
          td = @user_name
          td = spot.category.name
          td = spot.name
          td = spot.address
          td = spot.postal_code
          td = spot.neer_station
          td = link_to 'Show', spot
          td = link_to 'Edit', edit_spot_path(spot)
          td = link_to 'Destroy', spot, data: { confirm: 'Are you sure?' }, method: :delete

br

.container
  = link_to '新規登録', new_spot_path, class:"btn waves-effect waves-light"